title: BethZ
description: Technology strategist, builder, coach.
url: "https://www.bethz.com"
baseurl: ""

# Blog settings
permalink: /blog/:year/:month/:title/
paginate: 5

# Build
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
future: true
